export const seedDoctors = [
  {
    id: 'd1',
    name: 'Dr. Asha Rao',
    specialty: 'General Physician',
    experienceYears: 12,
    rating: 4.8,
    location: 'Koramangala Clinic',
    fee: 500,
    bio: 'Dr. Asha Rao specializes in family medicine and preventive care, helping patients manage everyday health concerns.',
    workDays: [1, 2, 3, 4, 5],
  },
  {
    id: 'd2',
    name: 'Dr. Vikram Shah',
    specialty: 'Cardiologist',
    experienceYears: 18,
    rating: 4.9,
    location: 'Heartcare Center',
    fee: 900,
    bio: 'Dr. Vikram Shah is a senior cardiologist with expertise in interventional cardiology and heart health screening.',
    workDays: [1, 2, 3, 4, 6],
  },
  {
    id: 'd3',
    name: 'Dr. Meera Nair',
    specialty: 'Dermatologist',
    experienceYears: 8,
    rating: 4.6,
    location: 'Skin & Glow Clinic',
    fee: 600,
    bio: 'Dr. Meera Nair treats skin, hair, and nail conditions, with a focus on acne and cosmetic dermatology.',
    workDays: [2, 3, 4, 5, 6],
  },
  {
    id: 'd4',
    name: 'Dr. Rahul Kapoor',
    specialty: 'Pediatrician',
    experienceYears: 15,
    rating: 4.9,
    location: 'Little Steps Children Hospital',
    fee: 550,
    bio: 'Dr. Rahul Kapoor cares for infants, children, and adolescents, focusing on growth and preventive vaccination.',
    workDays: [1, 2, 3, 4, 5],
  },
  {
    id: 'd5',
    name: 'Dr. Priya Menon',
    specialty: 'Dentist',
    experienceYears: 10,
    rating: 4.7,
    location: 'Bright Smile Dental',
    fee: 400,
    bio: 'Dr. Priya Menon offers general and cosmetic dentistry, including cleanings, fillings, and whitening.',
    workDays: [1, 3, 4, 5, 6],
  },
  {
    id: 'd6',
    name: 'Dr. Sanjay Gupta',
    specialty: 'Orthopedic',
    experienceYears: 20,
    rating: 4.8,
    location: 'Bone & Joint Institute',
    fee: 800,
    bio: 'Dr. Sanjay Gupta specializes in joint replacement, sports injuries, and spine care.',
    workDays: [1, 2, 4, 5, 6],
  },
  {
    id: 'd7',
    name: 'Dr. Kavita Iyer',
    specialty: 'ENT Specialist',
    experienceYears: 9,
    rating: 4.5,
    location: 'ENT Care Clinic',
    fee: 500,
    bio: 'Dr. Kavita Iyer treats ear, nose, and throat conditions including sinus issues and hearing concerns.',
    workDays: [1, 2, 3, 5, 6],
  },
  {
    id: 'd8',
    name: 'Dr. Arjun Malhotra',
    specialty: 'Psychiatrist',
    experienceYears: 11,
    rating: 4.9,
    location: 'Mindwell Clinic',
    fee: 700,
    bio: 'Dr. Arjun Malhotra helps patients manage anxiety, depression, and other mental health conditions.',
    workDays: [1, 2, 3, 4, 5],
  },
  {
    id: 'd9',
    name: 'Dr. Neha Verma',
    specialty: 'Gynecologist',
    experienceYears: 14,
    rating: 4.8,
    location: "Women's Health Center",
    fee: 650,
    bio: "Dr. Neha Verma provides comprehensive women's health care, including prenatal and reproductive health.",
    workDays: [2, 3, 4, 5, 6],
  },
]
